<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Logger\WoowzLib.Logger.csproj" />
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Render.OpenGL\WoowzLib.Render.OpenGL.csproj" />
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Interface.ImGUI.OpenGL\WoowzLib.Interface.ImGUI.OpenGL.csproj" />
    </ItemGroup>

</Project>
