<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        
        <!-- для того что-бы был 1 файл -->
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>

        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
        
        <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WoowzEngine\WoowzEngine.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NativeFileDialogSharp" Version="0.5.0" />
    </ItemGroup>

</Project>
