<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.0.2</Version>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Window.GLFW\WoowzLib.Window.GLFW.csproj" />
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Logger\WoowzLib.Logger.csproj" />
        <ProjectReference Include="..\WoowzEngineRender\WoowzEngineRender.csproj" />
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Loader.Image\WoowzLib.Loader.Image.csproj" />
        <ProjectReference Include="..\..\..\WoowzLib\WoowzLib\WoowzLib.Loader.Geometry\WoowzLib.Loader.Geometry.csproj" />
    </ItemGroup>

    <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
        <Exec Command="&quot;W:\Other\WoowzLib\CSVersionUpdater\CSVersionUpdater\bin\Debug\net8.0\CSVersionUpdater.exe&quot; &quot;$(MSBuildProjectFullPath)&quot;" />
    </Target>
    
</Project>