<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\..\WoowzLib\WoowzLib\WoowzLib.Window.GLFW\WoowzLib.Window.GLFW.csproj" />
        <ProjectReference Include="..\..\WoowzLib\WoowzLib\WoowzLib.Logger\WoowzLib.Logger.csproj" />
        <ProjectReference Include="..\..\WoowzLib\WoowzLib\WoowzLib.Render.Vulkan\WoowzLib.Render.Vulkan.csproj" />
        <ProjectReference Include="..\..\WoowzLib\WoowzLib\WoowzLib.Interface.ImGUI\WoowzLib.Interface.ImGUI.csproj" />
    </ItemGroup>

</Project>
